export default {
  bank_selfnum: '查询，在本银行机构的申请次数',
  bank_allnum: '查询，在银行机构申请次数',
  bank_orgnum: '查询，在银行机构申请机构数',
  nbank_selfnum: '查询，在本非银机构申请次数',
  nbank_allnum: '查询，在非银机构申请次数',
  nbank_p2p_allnum: '查询，在非银机构-p2p申请次数',
  nbank_mc_allnum: '查询，在非银机构-小贷申请次数',
  nbank_ca_allnum: '查询，在非银机构-现金类分期申请次数',
  nbank_cf_allnum: '查询，在非银机构-消费类分期申请次数',
  nbank_com_allnum: '查询，在非银机构-代偿类分期申请次数',
  nbank_oth_allnum: '查询，在非银机构-其他申请次数',
  nbank_orgnum: '查询，在非银机构申请机构数',
  nbank_p2p_orgnum: '查询，在非银机构-p2p申请机构数',
  nbank_mc_orgnum: '查询，在非银机构-小贷申请机构数',
  nbank_ca_orgnum: '查询，在非银机构-现金类分期申请机构数',
  nbank_cf_orgnum: '查询，在非银机构-消费类分期申请机构数',
  nbank_com_orgnum: '查询，在非银机构-代偿类分期申请机构数',
  nbank_oth_orgnum: '查询，在非银机构-其他申请机构数'
}
